### PR TITLE
Fix API returning 500 when an image is supplied with an unknown channel

### LINKED ISSUE #822: Invalid DeliveryChannel returns 500
If an invalid deliveryChannel value is specified when making API request it results in a 500, rather than a 400. This happens whether using the 'full' format or one of the reduced formats. 

E.g. the following would result in a 500.

```
"deliveryChannels": ["foo"]

"deliveryChannels": [{ "channel": "foo" } ]

"deliveryChannels": [{ "channel": "foo", "policy": "default" } ]
```

### PR DESCRIPTION
**Pull request by griffri**
Resolves #822 and WDC-85

This PR fixes a bug which caused the API to return 500 on attempting to PUT an image containing an unknown channel. It also adds a test confirming that 400 is sent in this scenario.

### CODE REVIEW

**Review by JackLewis-digirati — APPROVED** [review]

File: src/protagonist/API/Features/Image/Validation/HydraImageValidator.cs [hunk 1]
```diff
@@ -111,4 +111,16 @@ private void DeliveryChannelDependantValidation()
...
                 $"ImageOptimisationPolicy '{KnownImageOptimisationPolicy.UseOriginalId}' only valid for image delivery-channel");
     }
+
+    private bool DeliveryChannelIsValidForMediaType(string channel, string mediaType)
+    {
+        try
+        {
+            return AssetDeliveryChannels.IsChannelValidForMediaType(channel, mediaType);
+        }
+        catch(ArgumentOutOfRangeException)
```
Comment (donaldgray) [inline src/protagonist/API/Features/Image/Validation/HydraImageValidator.cs:121]: Would it be cleaner to optionally throw an exception in `IsChannelValidForMediaType` if we know that it could be invalid in some instances?

```cs
static bool IsChannelValidForMediaType(string deliveryChannel, string mediaType);

static bool IsChannelValidForMediaType(string deliveryChannel, string mediaType, bool throwIfUnknownChannel = true);
```

File: src/protagonist/API.Tests/Integration/ModifyAssetTests.cs [hunk 2]
```diff
@@ -279,7 +279,32 @@ public async Task Put_NewImageAsset_Creates_Asset_WhileIgnoringCustomDefaultDeli
                                                                 x.DeliveryChannelPolicyId == KnownDeliveryChannelPolicies.ImageDefault);
         asset.ImageDeliveryChannels.Should().ContainSingle(x => x.Channel == "thumbs");
     }
-    
+
+    [Fact]
+    public async Task Put_NewImageAsset_BadRequest_WhenDeliveryChannelInvalid()
+    {
+        // arrange
+        var assetId = new AssetId(99, 1, nameof(Put_NewImageAsset_BadRequest_WhenDeliveryChannelInvalid));
```
Comment (donaldgray) [inline src/protagonist/API.Tests/Integration/ModifyAssetTests.cs:287]: Use `AssetIdGenerator.GetAssetId()`

**Review by donaldgray — APPROVED** [review]

File: src/protagonist/API/Features/Image/Validation/HydraImageValidator.cs (hunk 1 above)
Comment (griffri) [reply src/protagonist/API/Features/Image/Validation/HydraImageValidator.cs:121]: I think it would be. It saves on similar handlers needing to be written elsewhere if needed, too.
