### PR TITLE
Adjunct bugfixes

### LINKED ISSUE #1084: Adjunct JSON validation issues
Catch-all ticket for issues related to the validation of JSON payloads for adjuncts:

### `"id"` is required when creating an adjunct via PUT

The documentation states that the `"id"` field should be optional when creating adjuncts via PUT:
https://deploy-preview-2--dlcs-docs.netlify.app/api-doc/adjuncts#id-1

But this isn't the behaviour currently seen on the development environment. Attempting to create an adjunct via PUT without specifying an `"id"` causes Protagonist to return the following error:

```JSON
{
    "@type": "Error",
    "statusCode": 400,
    "status": 400,
    "title": "Bad request",
    "detail": "'id' and '@id' must have a matching adjunct identifier",
    "instance": "https://api.dlcs.digirati.io/",
    "description": "'id' and '@id' must have a matching adjunct identifier"
}
```

### Language codes contained within `"language"` can be any size

See https://github.com/dlcs/protagonist/issues/1073#issue-3686684418:
> language: Optional. The language of an adjunct's content, if applicable. The value is a JSON array of ISO language codes (sub-codes are allowed). No validation other than field length.

There's currently no validation for field length:
```JSON
{
    "@context": "https://api.dlcs.digirati.io/contexts/Adjunct.jsonld",
    "@id": "https://api.dlcs.digirati.io/customers/52/spaces/299/images/world-of-cheese/adjuncts/long-language-value-test",
    "@type": "Dataset",
    "id": "long-language-value-test",
    "mediaType": "text/xml",
    "iiifLink": "seeAlso",
    "profile": "http://www.loc.gov/standards/alto/v3/alto.xsd",
    "label": {
        "en": [
            "METS-ALTO XML"
        ]
    },
    "language": [
        "llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch"
    ],
    "externalId": "https://dlcsstage-public-test-objects.s3.eu-west-1.amazonaws.com/images-with-text/b29820947_0014.jp2.xml",
    "publicId": "https://dlcsstage-public-test-objects.s3.eu-west-1.amazonaws.com/images-with-text/b29820947_0014.jp2.xml",
    "created": "2026-01-13T16:41:12.7985352Z",
    "finished": "2026-01-13T16:41:12.7985352Z"
}
```

### Adjunct `"id"` can contain whitespace characters
It's currently possible to create an adjunct with an ID containing whitespace characters:
```JSON
{
    "@context": "https://api.dlcs.digirati.io/contexts/Adjunct.jsonld",
    "@id": "https://api.dlcs.digirati.io/customers/52/spaces/299/images/world-of-cheese/adjuncts/  foo             bar         baz   ",
    "@type": "Dataset",
    "id": "  foo             bar         baz   ",
    "mediaType": "text/xml",
    "iiifLink": "seeAlso",
    "profile": "http://www.loc.gov/standards/alto/v3/alto.xsd",
    "label": {
        "en": [
            "METS-ALTO XML"
        ]
    },
    "externalId": "https://dlcsstage-public-test-objects.s3.eu-west-1.amazonaws.com/images-with-text/b29820947_0014.jp2.xml",
    "publicId": "https://dlcsstage-public-test-objects.s3.eu-west-1.amazonaws.com/images-with-text/b29820947_0014.jp2.xml",
    "created": "2026-01-13T16:51:18.5284480Z",
    "finished": "2026-01-13T16:51:18.5284480Z"
}
```
This can be done via both POST and PUT (With a URL containing `.../adjuncts/  foo             bar         baz   `)

### Adjuncts can share a nearly identical `"id"` when cased differently
It's possible to have two adjuncts share the same ID, but with different casing:
```JSON
[
    {
        "@context": "https://api.dlcs.digirati.io/contexts/Adjunct.jsonld",
        "@id": "https://api.dlcs.digirati.io/customers/52/spaces/299/images/world-of-cheese/adjuncts/test",
        "@type": "Dataset",
        "id": "test",
        "mediaType": "text/xml",
        "iiifLink": "seeAlso",
        "profile": "http://www.loc.gov/standards/alto/v3/alto.xsd",
        "label": {
            "en": [
                "METS-ALTO XML2"
            ]
        },
        "language": [
            "en"
        ],
        "externalId": "https://dlcsstage-public-test-objects.s3.eu-west-1.amazonaws.com/images-with-text/b29820947_0014.jp2.xml",
        "publicId": "https://dlcsstage-public-test-objects.s3.eu-west-1.amazonaws.com/images-with-text/b29820947_0014.jp2.xml",
        "created": "2026-01-13T15:21:46.5468020Z",
        "finished": "2026-01-13T15:21:46.5468020Z"
    },
    {
        "@context": "https://api.dlcs.digirati.io/contexts/Adjunct.jsonld",
        "@id": "https://api.dlcs.digirati.io/customers/52/spaces/299/images/world-of-cheese/adjuncts/Test",
        "@type": "Dataset",
        "id": "Test",
        "mediaType": "text/xml",
        "iiifLink": "seeAlso",
        "profile": "http://www.loc.gov/standards/alto/v3/alto.xsd",
        "label": {
            "en": [
                "METS-ALTO XML2"
            ]
        },
        "language": [
            "en"
        ],
        "externalId": "https://dlcsstage-public-test-objects.s3.eu-west-1.amazonaws.com/images-with-text/b29820947_0014.jp2.xml",
        "publicId": "https://dlcsstage-public-test-objects.s3.eu-west-1.amazonaws.com/images-with-text/b29820947_0014.jp2.xml",
        "created": "2026-01-13T15:21:49.4681130Z",
        "finished": "2026-01-13T15:21:49.4681130Z"
    }
]
```

### Incorrect status code creating asset for not found Asset

If I attempt to create an adjunct for an asset that doesn't exist I receive a 500 status code but ACs for both POST and PUT have

> 404 if asset doesn't exist.

but I receive:

```json
{
    "@type": "Error",
    "statusCode": 500,
    "status": 500,
    "title": "Create or update adjunct failed",
    "detail": "An error occurred while saving the entity changes. See the inner exception for details.",
    "instance": "https://api.dlcs.digirati.io",
    "description": "An error occurred while saving the entity changes. See the inner exception for details."
}
```

### LINKED ISSUE #1085: Adjunct `"size"` value is ignored
You can create an adjunct with user-defined `"size"` value using a payload like so:
```JSON
{
    "id": "size-test-2",
    "externalId": "https://dlcsstage-public-test-objects.s3.eu-west-1.amazonaws.com/images-with-text/b29820947_0014.jp2.xml",
    "@type": "Dataset",
    "mediaType": "text/xml",
    "profile": "http://www.loc.gov/standards/alto/v3/alto.xsd",
    "label": { "en": [ "METS-ALTO XML" ] },
    "size": 36032,
    "iiifLink": "seeAlso",
    "language": [ "en" ]
}
```
And this will be accepted as a valid payload for an adjunct - but `"size"` isn't visible in the returned JSON (or from requesting the created adjunct via GET)
```JSON
{
    "@context": "https://api.dlcs.digirati.io/contexts/Adjunct.jsonld",
    "@id": "https://api.dlcs.digirati.io/customers/52/spaces/299/images/world-of-cheese/adjuncts/size-test",
    "@type": "Dataset",
    "id": "size-test",
    "mediaType": "text/xml",
    "iiifLink": "seeAlso",
    "profile": "http://www.loc.gov/standards/alto/v3/alto.xsd",
    "label": {
        "en": [
            "METS-ALTO XML"
        ]
    },
    "language": [
        "en"
    ],
    "externalId": "https://dlcsstage-public-test-objects.s3.eu-west-1.amazonaws.com/images-with-text/b29820947_0014.jp2.xml",
    "publicId": "https://dlcsstage-public-test-objects.s3.eu-west-1.amazonaws.com/images-with-text/b29820947_0014.jp2.xml",
    "created": "2026-01-14T11:13:29.6555373Z",
    "finished": "2026-01-14T11:13:29.6555374Z"
}
```
[#1073](https://github.com/dlcs/protagonist/issues/1073) mentions that `"size"` should be useable at this stage, so this appears to be a bug:

> Optional. The size in bytes of the adjunct. For adjuncts created with externalId you can supply this yourself.

The same issue occurs with PUT.

### PR DESCRIPTION
**Pull request by donaldgray**
Fixes #1084 and fixes #1085

There are a few fixes from the above 2 tickets:

## "id" is required when creating an adjunct via PUT

This was related to validation of `.ModelId` in `HydraAdjunctValidator` by comparing it to `.Id`. This was unnecessary as the validation is already happening in `AdjunctController.PutAdjunct()`. Also extended check in controller to ignore `""` as well as explicitly `null` `"id"` values in PUT body.

Also introduced a new default ctor for Adjunct hydra model, this will be used when deserialising. The other ctor will be used when constructing the full model with hypermedia links, this takes values like customer and space that aren't in the actual payload received so we'd never be able to fully use this one.

## Language codes contained within "language" can be any size

Added `HydraAdjunctValidator` rule that all items in `language` have max of 10 characters.

This is to handle ISO (`en`, `fra`) codes, sub-codes (`US-NY`, `GB-SCT`, `zh-Hans-CN`) and 'none' (thanks @stephenwf !)

## Adjunct "id" can contain whitespace characters

Added `HydraAdjunctValidator` rule to check that none of the provided characters are present in the exclusion list applied to assets, and verified length for does not exceed 200 chars.  

The exclusion list was added in #701, originally titled `RestrictedAssetIdCharacterString`, now renamed to `RestrictedResourceIdCharacterString`. I also added the default list to the basic `appsettings.json` - this avoids the need to configure the same `"RestrictedAssetIdCharacterString" = "\\ "` config for every deployment of Protagonist. 

> [!WARNING]
> This is a renamed property but all usages use the default character list so there'll be no practical change.
>
> The previous default was "\\ " but it's now "\\ /". The `/` character was caught for Assets when parsing but it's now explicitly included as an invalid character.

## Adjuncts can share a nearly identical "id" when cased differently

This was handled by adding a unique constraint to DB, `CREATE UNIQUE INDEX xx ON "Adjuncts" (LOWER("Id"), "AssetId");`. 

This means that `Id` value will fail if we try to write `Test` and `test` while still maintaining case-sensitive reads (ie GET `/Test` would work but GET `/test` wouldn't).

Left some comments in code but had to do this manually, via migration, rather than via EFCore as it's not supported.

## Incorrect status code creating asset for not found Asset

Extended `GetDatabaseError` to return new `DbForeignKeyConstraintError` type to allow identification of FK constraint errors.

## Adjunct "size" value is ignored

`size` mapping missing from mapping class

## Other changes

* Removed `AssetId` from Hydra model. This wasn't used anywhere and was ignored by serialiser so unnecessary.
* Changed `.AddTestAdjunct()` helper to be a fluent method off of an added `Asset` to make test setup simpler.
* Added default `now()` value to `Adjuncts.Created`. Still set manually, without it, for external adjuncts, the `Finished` date is earlier than `Created` which was odd but may be of use elsewhere.
* Set DB max length of `Adjunct` to match validated length.

> [!NOTE]
> Contains a migration

### CODE REVIEW

File: src/protagonist/DLCS.HydraModel/Adjunct.cs [hunk 1]
```diff
@@ -10,14 +10,21 @@ namespace DLCS.HydraModel;
...
+    
     public Adjunct(string baseUrl, int customerId, int space, string assetId, string modelId)
     {
         ModelId = modelId;
         Init(baseUrl, true, customerId, space, assetId, ModelId);
     }
     
     [JsonProperty(Order = 3, PropertyName = "@type")]
-    public override required string Type { get; set; }
+    public override string? Type { get; set; }
```
Comment (JackLewis-digirati) [inline src/protagonist/DLCS.HydraModel/Adjunct.cs:27]: I know this was to do with getting different validation errors - is it worth using the `= null!` instead?

**Review by griffri — APPROVED** [review]
LGTM

**Review by JackLewis-digirati — APPROVED** [review]

File: src/protagonist/DLCS.HydraModel/Adjunct.cs (hunk 1 above)
Comment (donaldgray) [reply src/protagonist/DLCS.HydraModel/Adjunct.cs:27]: Using `string` will result in `required string` being returned. `string?` allows the model binding to 'pass' to hit FluentValidator, so `= null!` isn't required.

Will take a note to revisit - leveraging the automatic binding/validation is better than letting it flow through to controller then rejecting.
